## A. Build a baseline model (5 marks)

Use the Keras library to build a neural network with the following:

- One hidden layer of 10 nodes, and a ReLU activation function

- Use the adam optimizer and the mean squared error as the loss function.

1. Randomly split the data into a training and test sets by holding 30% of the data for testing. You can use the train_test_splithelper function from Scikit-learn.

2. Train the model on the training data using 50 epochs.

3. Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. You can use the mean_squared_error function from Scikit-learn.

4. Repeat steps 1 - 3, 50 times, i.e., create a list of 50 mean squared errors.

5. Report the mean and the standard deviation of the mean squared errors.

Submit your Jupyter Notebook with your code and comments.

In [2]:
import pandas as pd
import numpy as np
import keras
#import sklearn
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [3]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29

In [4]:
concrete_data_columns = concrete_data.columns

In [5]:
target = concrete_data['Strength']
target.head(10)

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
5    47.03
6    43.70
7    36.45
8    45.85
9    39.29
Name: Strength, dtype: float64

In [6]:
predictors = concrete_data.iloc[:, :-1]
predictors.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28

In [7]:
n_cols = predictors.shape[1]
def regression_model():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [8]:
model = regression_model()

In [9]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3)
    #Train and test the model at the same time
    res = model.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 173.12245178222656
Cycle #2: mean_squared_error 120.31755828857422
Cycle #3: mean_squared_error 83.35787963867188
Cycle #4: mean_squared_error 78.4520034790039
Cycle #5: mean_squared_error 72.07899475097656
Cycle #6: mean_squared_error 64.88055419921875
Cycle #7: mean_squared_error 59.46611404418945
Cycle #8: mean_squared_error 57.35518264770508
Cycle #9: mean_squared_error 46.278011322021484
Cycle #10: mean_squared_error 52.610713958740234
Cycle #11: mean_squared_error 49.1450080871582
Cycle #12: mean_squared_error 50.90869140625
Cycle #13: mean_squared_error 51.75603485107422
Cycle #14: mean_squared_error 45.81013488769531
Cycle #15: mean_squared_error 42.641963958740234
Cycle #16: mean_squared_error 45.3686408996582
Cycle #17: mean_squared_error 50.49171447753906
Cycle #18: mean_squared_error 48.75419616699219
Cycle #19: mean_squared_error 41.71453094482422
Cycle #20: mean_squared_error 48.945655822753906
Cycle #21: mean_squared_error 50.76065444946289
Cycle #22: mean_squared_error 47.392452239990234
Cycle #23: mean_squared_error 43.51711654663086
Cycle #24: mean_squared_error 43.045257568359375
Cycle #25: mean_squared_error 42.35652542114258
Cycle #26: mean_squared_error 45.65718078613281
Cycle #27: mean_squared_error 36.967979431152344
Cycle #28: mean_squared_error 44.11939239501953
Cycle #29: mean_squared_error 42.98481750488281
Cycle #30: mean_squared_error 44.339717864990234
Cycle #31: mean_squared_error 44.36562728881836
Cycle #32: mean_squared_error 37.878787994384766
Cycle #33: mean_squared_error 43.605255126953125
Cycle #34: mean_squared_error 42.61896514892578
Cycle #35: mean_squared_error 41.45210647583008
Cycle #36: mean_squared_error 40.752994537353516
Cycle #37: mean_squared_error 45.707942962646484
Cycle #38: mean_squared_error 41.14236068725586
Cycle #39: mean_squared_error 33.72196960449219
Cycle #40: mean_squared_error 39.7744140625
Cycle #41: mean_squared_error 40.417850494384766
Cycle #42: mean_squared_error 33.73565673828125
Cycle #43: mean_squared_error 41.773860931396484
Cycle #44: mean_squared_error 37.104042053222656
Cycle #45: mean_squared_error 38.66555404663086
Cycle #46: mean_squared_error 40.986263275146484
Cycle #47: mean_squared_error 35.89746856689453
Cycle #48: mean_squared_error 41.76242446899414
Cycle #49: mean_squared_error 31.68453598022461
Cycle #50: mean_squared_error 43.38166046142578

In [10]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 50.42053741455078
The standard deviation of the mean squared errors: 22.744467214340947

## B. Normalize the data (5 marks)

Repeat Part A but use a normalized version of the data. Recall that one way to normalize the data is by subtracting the mean from the individual predictors and dividing by the standard deviation.

How does the mean of the mean squared errors compare to that from Step A?

In [11]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
5,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,0.701883
6,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
7,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597
8,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,-0.279597
9,1.854740,-0.856472,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597

In [12]:
n_cols = predictors_norm.shape[1]
def regression_model2():
    model2 = Sequential()
    model2.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model2.add(Dense(1))
    
    model2.compile(optimizer='adam', loss='mean_squared_error')
    return model2

model2 = regression_model2()

In [13]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model2.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 331.09735107421875
Cycle #2: mean_squared_error 175.93215942382812
Cycle #3: mean_squared_error 112.48912811279297
Cycle #4: mean_squared_error 86.62244415283203
Cycle #5: mean_squared_error 85.54496002197266
Cycle #6: mean_squared_error 77.70238494873047
Cycle #7: mean_squared_error 68.52947998046875
Cycle #8: mean_squared_error 64.87188720703125
Cycle #9: mean_squared_error 71.45491027832031
Cycle #10: mean_squared_error 64.7799072265625
Cycle #11: mean_squared_error 54.74555206298828
Cycle #12: mean_squared_error 42.58247756958008
Cycle #13: mean_squared_error 46.068382263183594
Cycle #14: mean_squared_error 41.5377311706543
Cycle #15: mean_squared_error 48.05289840698242
Cycle #16: mean_squared_error 42.4818000793457
Cycle #17: mean_squared_error 40.678829193115234
Cycle #18: mean_squared_error 33.34059143066406
Cycle #19: mean_squared_error 48.24763870239258
Cycle #20: mean_squared_error 32.58556365966797
Cycle #21: mean_squared_error 34.43437957763672
Cycle #22: mean_squared_error 40.412235260009766
Cycle #23: mean_squared_error 39.929622650146484
Cycle #24: mean_squared_error 35.845787048339844
Cycle #25: mean_squared_error 39.02644348144531
Cycle #26: mean_squared_error 37.59023666381836
Cycle #27: mean_squared_error 35.890716552734375
Cycle #28: mean_squared_error 37.23619842529297
Cycle #29: mean_squared_error 38.89131546020508
Cycle #30: mean_squared_error 39.69873046875
Cycle #31: mean_squared_error 35.92953109741211
Cycle #32: mean_squared_error 37.842124938964844
Cycle #33: mean_squared_error 35.231689453125
Cycle #34: mean_squared_error 32.50685119628906
Cycle #35: mean_squared_error 38.311920166015625
Cycle #36: mean_squared_error 38.85222625732422
Cycle #37: mean_squared_error 39.74074172973633
Cycle #38: mean_squared_error 38.621585845947266
Cycle #39: mean_squared_error 39.77686309814453
Cycle #40: mean_squared_error 38.6234130859375
Cycle #41: mean_squared_error 31.761123657226562
Cycle #42: mean_squared_error 38.712581634521484
Cycle #43: mean_squared_error 31.288143157958984
Cycle #44: mean_squared_error 39.63265609741211
Cycle #45: mean_squared_error 37.206600189208984
Cycle #46: mean_squared_error 34.65148162841797
Cycle #47: mean_squared_error 39.940608978271484
Cycle #48: mean_squared_error 35.499977111816406
Cycle #49: mean_squared_error 28.59486961364746
Cycle #50: mean_squared_error 44.37532424926758

In [14]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 53.70804111480713
The standard deviation of the mean squared errors: 46.65245749754402

The mean and the standard deviation of the mean squared errors in case A are less than in case B; however the difference is small. A single hidden layer isn't enough to provide accurate results, which is highlighted by data normalization not helping much. Error is huge for both A and B.

## C. Increate the number of epochs (5 marks)

Repeat Part B but use 100 epochs this time for training.

How does the mean of the mean squared errors compare to that from Step B?

In [15]:
def regression_model3():
    model3 = Sequential()
    model3.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model3.add(Dense(1))
    
    model3.compile(optimizer='adam', loss='mean_squared_error')
    return model3

model3 = regression_model3()

In [16]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model3.fit(X_train, y_train, epochs=100, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 206.67446899414062
Cycle #2: mean_squared_error 105.45579528808594
Cycle #3: mean_squared_error 87.46231842041016
Cycle #4: mean_squared_error 63.511837005615234
Cycle #5: mean_squared_error 58.96611404418945
Cycle #6: mean_squared_error 37.706138610839844
Cycle #7: mean_squared_error 41.92133712768555
Cycle #8: mean_squared_error 38.766292572021484
Cycle #9: mean_squared_error 47.030757904052734
Cycle #10: mean_squared_error 38.80453872680664
Cycle #11: mean_squared_error 39.45164108276367
Cycle #12: mean_squared_error 33.34770965576172
Cycle #13: mean_squared_error 33.451324462890625
Cycle #14: mean_squared_error 34.805267333984375
Cycle #15: mean_squared_error 36.534576416015625
Cycle #16: mean_squared_error 37.64856719970703
Cycle #17: mean_squared_error 35.87163543701172
Cycle #18: mean_squared_error 33.88492202758789
Cycle #19: mean_squared_error 29.022493362426758
Cycle #20: mean_squared_error 32.95246124267578
Cycle #21: mean_squared_error 29.53034210205078
Cycle #22: mean_squared_error 29.94969367980957
Cycle #23: mean_squared_error 31.607648849487305
Cycle #24: mean_squared_error 29.025352478027344
Cycle #25: mean_squared_error 27.084692001342773
Cycle #26: mean_squared_error 33.0079460144043
Cycle #27: mean_squared_error 29.95679473876953
Cycle #28: mean_squared_error 29.001367568969727
Cycle #29: mean_squared_error 29.749462127685547
Cycle #30: mean_squared_error 33.17572021484375
Cycle #31: mean_squared_error 31.627012252807617
Cycle #32: mean_squared_error 30.679914474487305
Cycle #33: mean_squared_error 29.484447479248047
Cycle #34: mean_squared_error 29.55500602722168
Cycle #35: mean_squared_error 28.636171340942383
Cycle #36: mean_squared_error 29.209108352661133
Cycle #37: mean_squared_error 33.64134216308594
Cycle #38: mean_squared_error 25.504940032958984
Cycle #39: mean_squared_error 27.847993850708008
Cycle #40: mean_squared_error 23.020734786987305
Cycle #41: mean_squared_error 26.44139289855957
Cycle #42: mean_squared_error 23.941993713378906
Cycle #43: mean_squared_error 26.116783142089844
Cycle #44: mean_squared_error 22.5225772857666
Cycle #45: mean_squared_error 30.240161895751953
Cycle #46: mean_squared_error 27.81819725036621
Cycle #47: mean_squared_error 26.118011474609375
Cycle #48: mean_squared_error 27.221416473388672
Cycle #49: mean_squared_error 28.852222442626953
Cycle #50: mean_squared_error 30.66831398010254

In [17]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 38.69013916015625
The standard deviation of the mean squared errors: 28.146922416951334

The mean and the standard deviation of the mean squared errors in case C are each bigger than the respective ones in case B. In both cases, error is huge. Once again, a single hidden layer isn't enough. The increased number of epochs doesn't do much.

## D. Increase the number of hidden layers (5 marks)

Repeat part B but use a neural network with the following instead:

- Three hidden layers, each of 10 nodes and ReLU activation function.

How does the mean of the mean squared errors compare to that from Step B?

In [18]:
def regression_model4():
    model4 = Sequential()
    model4.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(1))
    
    model4.compile(optimizer='adam', loss='mean_squared_error')
    return model4

In [19]:
model4 = regression_model4()

In [20]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model4.fit(X_train, y_train, epochs=100, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 54.63418960571289
Cycle #2: mean_squared_error 36.95528793334961
Cycle #3: mean_squared_error 32.67463684082031
Cycle #4: mean_squared_error 33.36668014526367
Cycle #5: mean_squared_error 23.52497100830078
Cycle #6: mean_squared_error 29.771739959716797
Cycle #7: mean_squared_error 29.193105697631836
Cycle #8: mean_squared_error 27.590810775756836
Cycle #9: mean_squared_error 24.573148727416992
Cycle #10: mean_squared_error 22.97249984741211
Cycle #11: mean_squared_error 27.629661560058594
Cycle #12: mean_squared_error 21.35690689086914
Cycle #13: mean_squared_error 27.77794075012207
Cycle #14: mean_squared_error 26.91657829284668
Cycle #15: mean_squared_error 24.94684410095215
Cycle #16: mean_squared_error 25.2001895904541
Cycle #17: mean_squared_error 21.430540084838867
Cycle #18: mean_squared_error 22.438024520874023
Cycle #19: mean_squared_error 31.088424682617188
Cycle #20: mean_squared_error 22.76445960998535
Cycle #21: mean_squared_error 25.906211853027344
Cycle #22: mean_squared_error 20.343019485473633
Cycle #23: mean_squared_error 22.503662109375
Cycle #24: mean_squared_error 19.043729782104492
Cycle #25: mean_squared_error 22.17780876159668
Cycle #26: mean_squared_error 21.329633712768555
Cycle #27: mean_squared_error 20.27046775817871
Cycle #28: mean_squared_error 24.966480255126953
Cycle #29: mean_squared_error 19.21079444885254
Cycle #30: mean_squared_error 21.392404556274414
Cycle #31: mean_squared_error 24.30084991455078
Cycle #32: mean_squared_error 18.232507705688477
Cycle #33: mean_squared_error 23.74968719482422
Cycle #34: mean_squared_error 25.585041046142578
Cycle #35: mean_squared_error 19.842370986938477
Cycle #36: mean_squared_error 21.049781799316406
Cycle #37: mean_squared_error 20.271703720092773
Cycle #38: mean_squared_error 19.22556495666504
Cycle #39: mean_squared_error 18.604141235351562
Cycle #40: mean_squared_error 17.980165481567383
Cycle #41: mean_squared_error 18.955984115600586
Cycle #42: mean_squared_error 20.25285530090332
Cycle #43: mean_squared_error 21.32691764831543
Cycle #44: mean_squared_error 16.199932098388672
Cycle #45: mean_squared_error 20.849340438842773
Cycle #46: mean_squared_error 22.099102020263672
Cycle #47: mean_squared_error 21.47260856628418
Cycle #48: mean_squared_error 17.737199783325195
Cycle #49: mean_squared_error 20.73442840576172
Cycle #50: mean_squared_error 18.925403594970703

In [21]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 23.826928787231445
The standard deviation of the mean squared errors: 6.187892669977116

The mean and the standard deviation of the mean squared errors in case D are less than the respective values in cases A, B and C. It's also the only case where error is not as big as the previous ones, which means additional layers in the neural network are more impactful than increasing the number of epochs and normalizing the data as isolated actions. This, in turn, demonstrates why a single hidden layer in the previous cases wasn't enough to produce good results.